services:
  mongodb:
    image: mongo:7.0
    container_name: cityflow-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: cityflow2025
    networks:
      - cityflow-net

  mongo-express:
    image: mongo-express:1.0.2
    container_name: cityflow-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: cityflow2025
      ME_CONFIG_MONGODB_URL: mongodb://admin:cityflow2025@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: student
      ME_CONFIG_BASICAUTH_PASSWORD: nosql2025
    depends_on:
      - mongodb
    networks:
      - cityflow-net
  redis:
    image: redis:7-alpine
    container_name: cityflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass cityflow2025 --appendonly yes
    networks:
      - cityflow-net
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: cityflow-redis-commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local:redis:6379:0:cityflow2025
      HTTP_USER: student
      HTTP_PASSWORD: nosql2025
    depends_on:
      - redis
    networks:
      - cityflow-net
volumes:
  mongo_data:
  redis_data:

networks:
  cityflow-net:
    driver: bridge
